# Generated by Django 4.1 on 2023-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_client_remove_coversation_conver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
