# Generated by Django 4.1 on 2023-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_client_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
